on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

name: local-omopgenerics

jobs:
  local-omopgenerics:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools
          needs: check

      - name: Run tests with local source
        run: |
          Sys.setenv("DB_TO_TEST" = "local omopgenerics")
          devtools::test(reporter = test_reporter())
        shell: Rscript {0}
